name: Jekyll with search
description: Trying out Jekyll
markdown: redcarpet
pygments: true
baseurl: /jkls
url: http://ivandj.github.io/jkls
server: auto
safe: true
auto: true
permalink: :year-:month-:day/:title/